settings1:
    outputFile: 'artist_list_rap'  #name of the output file
    tag: 'rap' #search by tags
    filter_tags: 'rap, r&b, hip hop, hip-hop, rnb' #filters tags for search 


settings2:
    outputFile: 'artist_list_hip_hop'  #name of the output file
    tag: 'hip hop' #search by tags
    filter_tags: 'hip hop, hip-hop' #filters tags for search results