settings1:
    outputFile: 'artist_list_rap'  #name of the output file
    tag: 'rap' #search by tags
    filter_tags: 'rap, r&b, hip hop, hip-hop, rnb' #filters tags for search 


settings2:
    outputFile: 'artist_list_hip_hop'  #name of the output file
    tag: 'hip hop' #search by tags
    filter_tags: 'hip hop, hip-hop' #filters tags for search results


lda:
    topics: [3, 6, 8, 10, 12, 15]
    #alphas:  [0.09]
    #etas: [0.9]
    # alphas:  [0.01, 0.05, 0.05, 0.07, 0.09]
    # etas: [0.01, 0.05, 0.09, 0.1, 0.5, 0.9]
